const $=id=>document.getElementById(id);let token,latest,qrUrl;
let world;
fetch('/api/world').then(r=>r.json()).then(w=>{world=w;drawCoverage();}).catch(()=>notify('Coverage geometry unavailable'));
function drawCoverage(){const canvas=$('coverage-map'),w=canvas.clientWidth,h=canvas.clientHeight,d=Math.min(devicePixelRatio,2);if(!w||!world)return;canvas.width=w*d;canvas.height=h*d;const ctx=canvas.getContext('2d');ctx.scale(d,d);ctx.fillStyle='#f0f3e9';ctx.fillRect(0,0,w,h);const coverage=new Map((latest?.observations||[]).map(o=>[o.edge_id,o]));const scale=.34,point=p=>[w/2+p[0]*scale,h/2-p[1]*scale];for(const road of world.roads){if(road.internal)continue;const row=coverage.get(road.contract_edge_id);ctx.strokeStyle=row?.coverage==='fresh'?(row.slowdown>.5?'#c78950':'#6b9360'):'#c7cec1';ctx.lineWidth=Math.max(1,road.width*scale);ctx.beginPath();road.shape.map(point).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}ctx.fillStyle='#738568';ctx.font='bold 11px Segoe UI';ctx.fillText('LIG SQUARE',w/2+12,h/2-12);}
new ResizeObserver(drawCoverage).observe($('coverage-map'));
$('advisory-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/operator/advisory',{session_id:$('recipient').value,message:$('advisory-text').value});notify('Note sent · awaiting driver acknowledgment');$('advisory-text').value='';}catch(error){notify(error.message);}};
$('export').onclick=async()=>{try{const r=await fetch('/api/operator/export',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Export failed');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='traffix-phone-run.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){notify(error.message);}};
function notify(text){$('notice').textContent=text;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('notice').textContent='',7000);}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.detail||'Request rejected');return data;}
function table(headers,rows){const table=document.createElement('table'),head=table.createTHead().insertRow();headers.forEach(h=>{const th=document.createElement('th');th.textContent=h;head.append(th);});const body=table.createTBody();rows.forEach(values=>{const row=body.insertRow();values.forEach(v=>row.insertCell().textContent=v);});return table;}
function update(s){latest=s;$('run').textContent=s.run_id;$('clock').textContent=`${Math.floor(s.sim_time_s/60).toString().padStart(2,'0')}:${Math.floor(s.sim_time_s%60).toString().padStart(2,'0')}`;$('connected').textContent=s.sessions.filter(p=>p.connected).length;$('samples').textContent=s.accepted_uplinks;$('fresh').textContent=s.observations.filter(o=>o.coverage==='fresh').length;$('play-state').textContent=s.paused?'Simulation paused':'Simulation running';
 const select=$('vehicles'),previous=select.value;select.replaceChildren(...s.available_vehicles.map(v=>new Option(`${v.id} · ${v.type}`,v.id)));if([...select.options].some(o=>o.value===previous))select.value=previous;$('invite').disabled=!select.value;
 $('sessions').replaceChildren(s.sessions.length?table(['VEHICLE','LINK','SHARING'],s.sessions.map(p=>[p.vehicle_id,p.connected?'Connected':'Offline',p.reporting?'On':'Off'])):document.createTextNode('No phones joined yet.'));
 $('observations').replaceChildren(s.observations.length?table(['EDGE','COVERAGE','SPEED','PROBES'],s.observations.map(o=>[o.edge_id,o.coverage,o.mean_speed_mps===null?'Unknown':`${(o.mean_speed_mps*3.6).toFixed(1)} km/h`,o.distinct_probes_60s])):document.createTextNode('No phone uplinks. All road coverage is unknown.'));
 const usable=s.forecasts.filter(f=>f.predicted_slowdown!==null&&!['insufficient_history_or_coverage','intervention_active_no_action_forecast_disabled'].includes(f.reason));$('forecasts').textContent=usable.length?`${usable.length} prototype forecasts available; automatic control remains disabled.`:'Forecasts unavailable · awaiting sufficient fresh probes and history.';
 $('audit').replaceChildren(...(s.audit.length?s.audit.slice().reverse().map(a=>{const div=document.createElement('div');div.className='audit-row';div.textContent=`${a.vehicle_id} · ${a.category.replaceAll('_',' ')}`;const small=document.createElement('small');small.textContent=`Unverified driver report · ${a.sim_time_s.toFixed(1)}s simulation time`;div.append(small);return div;}):[document.createTextNode('No reports submitted.')]));
}
$('invite').onclick=async()=>{try{const result=await api('/api/operator/join',{vehicle_id:$('vehicles').value});if(!$('origin').value&&result.lan_addresses.length)$('origin').value=`http://${result.lan_addresses[0]}:${location.port||8001}`;const origin=new URL($('origin').value||location.origin);if(!['http:','https:'].includes(origin.protocol)||origin.username||origin.password)throw Error('Use a valid http or https laptop address');const link=new URL('/driver',origin.origin);link.hash=new URLSearchParams({code:result.join_code}).toString();$('join-code').textContent=result.join_code;$('phone-link').href=link.href;const response=await fetch('/api/join-qr?url='+encodeURIComponent(link.href),{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw Error('QR generation failed');if(qrUrl)URL.revokeObjectURL(qrUrl);qrUrl=URL.createObjectURL(await response.blob());$('qr').src=qrUrl;$('invitation').hidden=false;}catch(error){notify(error.message);}};
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const result=await api('/api/control',{action:b.dataset.action});$('control-status').textContent=`Confirmed by engine: ${b.dataset.action} · ${result.sim_time_s.toFixed(2)}s`;}catch(error){notify(error.message);}finally{b.disabled=false;}});
try{const r=await fetch('/api/operator/bootstrap');const data=await r.json();if(!r.ok)throw Error(data.detail);token=data.token;await poll();}catch(error){notify(error.message);$('invite').disabled=true;document.querySelectorAll('[data-action]').forEach(b=>b.disabled=true);}
async function poll(){try{update(await api('/api/operator/state'));drawCoverage();const recipient=$('recipient'),previous=recipient.value;recipient.replaceChildren(...latest.sessions.filter(s=>s.connected).map(s=>new Option(s.vehicle_id,s.session_id)));if([...recipient.options].some(o=>o.value===previous))recipient.value=previous;$('advisory-form').querySelector('button').disabled=!recipient.value;}catch(error){notify(error.message);}finally{setTimeout(poll,1000);}}
