const $=id=>document.getElementById(id);let claim,seq=Number(sessionStorage.getItem('traffix.seq')||0),ws,ready=false,sharing=false,frame,offer,own,world,center,follow=true,retries=0,heartbeat,reconnectTimer,pollTimer,confirmed=0,lastServer=0,pending=new Map(),sent=new Set();
const friendly={past_decision_edge:'You have passed the turn. Keep your original route.',too_late_for_safe_turn:'Too late for a safe turn. Keep your original route.',expired_advisory:'This offer expired. Keep your original route.',guidance_turned_off:'The operator turned guidance off. Keep your original route.',phone_evidence_unavailable:'Current phone evidence is unavailable. Keep your original route.'};
function notice(text){$('notice').textContent=text;}
function screen(which){for(const id of ['join','drive','guidance'])$(id).hidden=id!==which;draw();}
function reflect(){$('sharing').checked=sharing;$('sharing').disabled=!ready;$('sharing-status').textContent=sharing?'On · server-validated samples':'Off · your choice, always';$('report').disabled=!ready||frame?.payload.state!=='active';}
function send(type,payload,stamp=null){if(!ready&&type!=='session.hello')return;if(ws?.readyState!==WebSocket.OPEN)return;const n=++seq;sessionStorage.setItem('traffix.seq',seq);const m={v:1,type,msg_id:`msg.phone.${n}`,run_id:claim.run_id,sender_id:claim.session_id,seq:n,sim_time_s:stamp,payload};ws.send(JSON.stringify(m));pending.set(m.msg_id,type);return m.msg_id;}
function echo(){if(!ready||!sharing||frame?.payload.state!=='active'||sent.has(frame.payload.frame_id))return;const {frame_id,vehicle_id,pose}=frame.payload;sent.add(frame_id);if(sent.size>200)sent.delete(sent.values().next().value);send('probe.sample',{frame_id,vehicle_id,pose},frame.sim_time_s);}
async function pollOwn(){clearTimeout(pollTimer);if(!claim||!ready)return;try{const r=await fetch('/api/driver/state?'+new URLSearchParams({session_id:claim.session_id,run_id:claim.run_id}),{headers:{Authorization:'Bearer '+claim.token}});if(r.ok){own=await r.json();$('role').textContent=own.role;$('route-name').textContent=own.route_id==='route.demo.B'?'Route B · applied':'Route A';if(own.paused)$('stage').textContent='Simulation paused';if(offer&&own.offer&&['expired','cancelled','rejected'].includes(own.offer.status)){notice('This offer is no longer valid. Your original route continues.');offer=null;screen('drive');}draw();}}catch{}pollTimer=setTimeout(pollOwn,700);}
function connect(){clearTimeout(reconnectTimer);ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);const socket=ws;ws.onopen=()=>{if(ws===socket)send('session.hello',{token:claim.token,last_server_seq:lastServer});};ws.onmessage=e=>{if(ws!==socket)return;const m=JSON.parse(e.data);lastServer=m.seq;
 if(m.type==='session.ready'){ready=true;sharing=false;retries=0;offer=null;notice('');screen('drive');$('connection').textContent='Connected';$('vehicle').textContent=claim.vehicle_id;$('role').textContent=claim.vehicle_id.endsWith('rider')?'Rider':claim.vehicle_id.endsWith('auto')?'Auto driver':'Delivery driver';reflect();clearInterval(heartbeat);heartbeat=setInterval(()=>send('heartbeat',{visible:!document.hidden}),2000);clearTimeout(pollTimer);pollOwn();}
 if(m.type==='vehicle.frame'){frame=m;$('speed').textContent=m.payload.pose?Math.round(m.payload.pose.speed_mps*3.6):'—';$('stage').textContent=m.payload.state==='active'?(own?.paused?'Simulation paused':m.payload.pose.speed_mps<.1?'Vehicle stopped':'On the move'):'Journey finished';$('stamp').textContent=`Simulation time ${Math.floor(m.sim_time_s/60).toString().padStart(2,'0')}:${Math.floor(m.sim_time_s%60).toString().padStart(2,'0')}`;if(follow&&m.payload.pose)center=[m.payload.pose.x_m,m.payload.pose.y_m];if(offer&&m.sim_time_s>=offer.expires_sim_s){offer=null;screen('drive');notice('Offer expired. Original route continues.');}reflect();draw();echo();}
 if(m.type==='guidance'&&m.payload.kind==='reroute'){offer=m.payload;$('guidance-message').textContent=offer.message;$('guidance-status').textContent='Your route stays unchanged until the server confirms.';$('accept').disabled=$('ignore').disabled=false;$('accept').textContent='Take Route B';screen('guidance');}
 if(m.type==='ack'){const kind=pending.get(m.payload.in_reply_to);pending.delete(m.payload.in_reply_to);const p=m.payload;if(kind==='probe.toggle'&&p.status==='applied'){sharing=p.reason==='sharing_on';reflect();echo();}if(kind==='probe.sample'&&p.status==='applied')$('uplinks').textContent=`${++confirmed} samples confirmed`;if(kind==='driver.report')$('report-status').textContent=p.status==='received'?'Received · unverified, awaiting operator review.':friendly[p.reason]||p.reason.replaceAll('_',' ');if(kind==='driver.decision'){offer=null;screen('drive');notice(p.status==='applied'&&p.reason==='route_applied'?'Route B applied. The server confirmed your turn.':p.reason==='original_route_kept'?'Original route kept.':friendly[p.reason]||p.reason.replaceAll('_',' '));pollOwn();}else if(p.status==='rejected')notice(friendly[p.reason]||p.reason.replaceAll('_',' '));}
 };ws.onclose=e=>{if(ws!==socket)return;ready=false;sharing=false;offer=null;clearInterval(heartbeat);clearTimeout(pollTimer);reflect();$('connection').textContent='Offline';$('speed').textContent='—';$('stage').textContent='Position unavailable';frame=null;draw();if(e.code===1008&&e.reason!=='heartbeat_timeout'){sessionStorage.removeItem('traffix.claim');claim=null;screen('join');notice('Demo reset or session ended. Get a fresh code from the laptop.');return;}screen('drive');notice('Connection lost. Sharing is off. Retrying…');reconnectTimer=setTimeout(()=>claim&&connect(),Math.min(4000,1000*2**retries++));};}
$('claim').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const r=await fetch('/api/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({join_code:$('code').value.trim()})});const data=await r.json();if(!r.ok)throw Error(data.detail||'Join failed');claim=data;seq=confirmed=0;sent.clear();pending.clear();sessionStorage.setItem('traffix.claim',JSON.stringify(data));sessionStorage.setItem('traffix.seq','0');connect();}catch(error){notice(error.message.replaceAll('_',' '));}finally{b.disabled=false;}};
$('sharing').onchange=e=>{const enabled=e.target.checked;e.target.checked=sharing;send('probe.toggle',{enabled});};$('report').onclick=()=>{if(frame?.payload.state==='active')send('driver.report',{frame_id:frame.payload.frame_id,vehicle_id:claim.vehicle_id,category:'slow_traffic'},frame.sim_time_s);};function decide(choice){if(!offer||!ready)return;send('driver.decision',{advisory_id:offer.advisory_id,choice});$('accept').disabled=$('ignore').disabled=true;$('accept').textContent='Applying…';$('guidance-status').textContent='Waiting for server confirmation. Your route has not changed yet.';}$('accept').onclick=()=>decide('accept');$('ignore').onclick=()=>decide('ignore');$('recenter').onclick=()=>{follow=true;const p=frame?.payload.pose;if(p)center=[p.x_m,p.y_m];draw();};
const canvas=$('map'),ctx=canvas.getContext('2d');function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;const d=Math.min(devicePixelRatio,2);canvas.width=w*d;canvas.height=h*d;ctx.scale(d,d);ctx.fillStyle='#e0e8d8';ctx.fillRect(0,0,w,h);if(!world)return;const c=center||[0,0],scale=.85,point=p=>[(p[0]-c[0])*scale+w/2,h/2-(p[1]-c[1])*scale];for(const road of world.roads){if(road.internal)continue;const pts=road.shape.map(point);if(!pts.some(p=>p[0]>-200&&p[0]<w+200&&p[1]>-200&&p[1]<h+200))continue;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle='#c0ceba';ctx.lineWidth=Math.max(3,road.width*scale+3);ctx.stroke();ctx.strokeStyle='#fafcf2';ctx.lineWidth=Math.max(1,road.width*scale);ctx.stroke();}ctx.strokeStyle=own?.route_id==='route.demo.B'?'#23866e':'#6c8295';ctx.lineWidth=4;ctx.setLineDash([7,5]);for(const shape of own?.route_path||[]){ctx.beginPath();shape.map(point).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}ctx.setLineDash([]);const p=frame?.payload.pose;if(p){const xy=point([p.x_m,p.y_m]);ctx.beginPath();ctx.arc(...xy,18,0,Math.PI*2);ctx.fillStyle='#388f7133';ctx.fill();ctx.beginPath();ctx.arc(...xy,8,0,Math.PI*2);ctx.fillStyle='#244e3e';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='white';ctx.stroke();}}
let drag;canvas.onpointerdown=e=>{follow=false;canvas.setPointerCapture(e.pointerId);drag=[e.clientX,e.clientY,...(center||[0,0])];};canvas.onpointermove=e=>{if(drag){center=[drag[2]-(e.clientX-drag[0])/.85,drag[3]+(e.clientY-drag[1])/.85];draw();}};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;new ResizeObserver(draw).observe(canvas);fetch('/api/world').then(r=>r.json()).then(w=>{world=w;draw();}).catch(()=>notice('Map unavailable. Vehicle data can still connect.'));
function invitation(){const p=new URLSearchParams(location.hash.slice(1)),code=p.get('join')||p.get('code');if(!code)return false;const old=ws;ws=null;old?.close();claim=null;ready=false;sharing=false;seq=0;clearInterval(heartbeat);clearTimeout(pollTimer);clearTimeout(reconnectTimer);sessionStorage.removeItem('traffix.claim');sessionStorage.removeItem('traffix.seq');$('code').value=code;history.replaceState(null,'',location.pathname);screen('join');reflect();return true;}window.addEventListener('hashchange',invitation);if(!invitation()){try{claim=JSON.parse(sessionStorage.getItem('traffix.claim')||'null');if(claim)connect();}catch{sessionStorage.removeItem('traffix.claim');}}reflect();
