import {DemoScene} from './scene.js?v=2';
const $=id=>document.getElementById(id);let token,state,scene,busy=false,lastOk=performance.now();
async function api(url,body){const r=await fetch(url,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');return d;}
function notice(s){$('notice').textContent=s;}
async function command(body){if(busy)return;busy=true;try{await api('/api/control',body);await refresh();}catch(e){notice(e.message);}finally{busy=false;}}
$('play').onclick=()=>command(state.ended?{action:'reset',scenario:'rain',seed:42}:{action:state.paused?'play':'pause'});
$('rate').onclick=()=>command({action:'set_rate',rate:4});$('reset').onclick=()=>command({action:'reset',scenario:'rain',seed:42});$('top').onclick=()=>scene?.home(true);$('orbit').onclick=()=>scene?.home(false);
$('smart').onchange=async e=>{const enabled=e.target.checked;e.target.disabled=true;try{await api('/api/response/smart',{run_id:state.run_id,enabled});notice(enabled?'Smart control enabled. Eligible queued approaches receive bounded green extensions.':'Smart control off. Current phase finishes safely.');}catch(error){notice(error.message);}finally{e.target.disabled=false;await refresh();}};
async function refresh(){try{
 state=await api('/api/response');lastOk=performance.now();$('status').textContent=state.ended?'Complete':state.paused?'Paused':state.response.smart_enabled?'Smart control':'Fixed timing';$('play').disabled=false;$('play').textContent=state.ended?'New experiment':state.paused?'Start / resume':'Pause';$('smart').checked=state.response.smart_enabled;
 $('counts').textContent=`${state.metrics.active} vehicles · ${state.metrics.queued} stopped · ${state.metrics.mean_speed_kph??'—'} km/h average`;$('clock').textContent=`${state.sim_time_s.toFixed(1)} s`;$('mix').textContent=Object.entries(state.response.vehicle_types).map(([k,v])=>`${k}: ${v}`).join(' · ');$('integrity').textContent=`${state.metrics.arrived}/${state.metrics.scheduled} arrived · ${state.metrics.collisions} collisions · ${state.metrics.teleports} teleports`;$('carbon').textContent=`Modelled tailpipe CO₂: ${state.metrics.co2_kg.toFixed(3)} kg (SUMO estimate)`;scene.frame(state,[],[],{});
 const cards=state.response.signals.map((s,i)=>{const c=document.createElement('section');c.className='card';const h=document.createElement('h2');h.textContent=`Junction ${i+1} · ${s.count} vehicles · ${s.stopped} stopped`;const lights=document.createElement('p');lights.style.cssText='font-size:18px;line-height:1.7;overflow-wrap:anywhere';lights.textContent=[...s.state].map(x=>x==='G'||x==='g'?'🟢':x==='y'||x==='Y'?'🟡':'🔴').join(' ');const focus=document.createElement('button');focus.textContent='View junction';focus.className='secondary';focus.onclick=()=>{scene.focusSignal(s.id);$('viewport').scrollIntoView({behavior:'smooth',block:'center'});};const p=document.createElement('p');p.textContent=`Phase ${s.phase} · ${s.remaining_s.toFixed(1)} s remaining. ${s.reason}`;const list=document.createElement('p');list.textContent=s.lanes.filter(l=>l.count).map(l=>`${l.lane}: ${l.count} vehicles, ${l.speed_kph} km/h`).join(' / ')||'No vehicles on monitored approaches.';const b=document.createElement('button');b.className='primary';b.disabled=!s.recommended||busy||state.response.smart_enabled;b.textContent='Approve green extension';b.onclick=async()=>{try{await api('/api/response/extend',{run_id:state.run_id,signal_id:s.id,phase_key:s.phase_key});notice('Server confirmed green extension.');}catch(e){notice(e.message);}await refresh();};c.append(h,lights,focus,p,list,b);return c;});$('signals').replaceChildren(...cards);
 $('audit').textContent=state.response.audit.map(a=>`${a.sim_time_s.toFixed(1)}s: ${a.controller==='queue_responsive'?'SMART':'MANUAL'} ${a.signal_id}; ${a.previous_remaining_s.toFixed(1)} → ${a.remaining_s.toFixed(1)} s; queue ${a.queue}, opposing ${a.opposing_queue}`).join('\n')||'No extensions yet. Control waits for a queued protected green with receiving space.';
 }catch(e){if(performance.now()-lastOk>3000){$('status').textContent='Offline';$('play').disabled=true;notice(e.message);}}}
try{token=(await api('/api/operator/bootstrap')).token;const world=await api('/api/world');scene=new DemoScene(world,$('world'),$('viewport'),fps=>$('fps').textContent=`Rendering: ${fps.toFixed(1)} fps`);await refresh();setInterval(refresh,1000);}catch(e){notice(e.message);}
