// Browser-only explanation, independent of the real SUMO host. No claimed metrics.
const canvas=document.getElementById('traffic'),ctx=canvas.getContext('2d');
const smartButton=document.getElementById('smart'),pauseButton=document.getElementById('pause');
let cars=[],green='ew',stage='green',elapsed=0,spawn=0,smart=false,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,last=0;
const kinds=[{color:'#546b64',length:16,width:9,speed:63},{color:'#8a6db2',length:9,width:5,speed:75},{color:'#c19c51',length:12,width:10,speed:48}];
function waiting(direction){const stop=direction==='ew'?294:230;return cars.filter(c=>c.dir===direction&&c.position>stop-150&&c.position<=stop&&c.speed<4).length;}
function reset(){cars=[];green='ew';stage='green';elapsed=0;spawn=0;last=0;}
function labels(){smartButton.setAttribute('aria-pressed',String(smart));smartButton.textContent=smart?'Queue response enabled':'Enable queue response';pauseButton.setAttribute('aria-pressed',String(paused));pauseButton.textContent=paused?'Resume':'Pause';document.getElementById('policy').textContent=stage==='clearance'?'Clearance · both directions stopped':(smart?'Queue response':'Fixed timing')+' · '+(green==='ew'?'east–west green':'north–south green');document.getElementById('queue').textContent='Waiting vehicles: E–W '+waiting('ew')+' · N–S '+waiting('ns');}
smartButton.onclick=()=>{smart=!smart;labels();};pauseButton.onclick=()=>{paused=!paused;labels();};document.getElementById('reset').onclick=()=>{reset();labels();};document.getElementById('demand').onchange=reset;
function step(dt){elapsed+=dt;spawn+=dt;
 if(stage==='clearance'){if(elapsed>=1.5){green=green==='ew'?'ns':'ew';stage='green';elapsed=0;}}
 else if((!smart&&elapsed>=8)||(smart&&elapsed>=4&&((waiting(green==='ew'?'ns':'ew')>waiting(green)+1)||elapsed>=14))){stage='clearance';elapsed=0;}
 if(spawn>.75){spawn=0;const busy=document.getElementById('demand').value==='busy';const n=busy?3:2;for(let i=0;i<n;i++){const dir=busy?(i<2?'ew':'ns'):(i?'ns':'ew'),lane=i%2;if(!cars.some(c=>c.dir===dir&&c.lane===lane&&c.position<22)){const kind=kinds[Math.floor(Math.random()*kinds.length)];cars.push({dir,lane,position:-20,speed:0,kind});}}}
 for(const dir of ['ew','ns'])for(const lane of [0,1]){const group=cars.filter(c=>c.dir===dir&&c.lane===lane).sort((a,b)=>b.position-a.position);let ahead=Infinity;for(const c of group){let limit=ahead-c.kind.length-11;const stop=dir==='ew'?294:230;if(c.position<=stop&&(stage!=='green'||green!==dir))limit=Math.min(limit,stop);const next=Math.min(c.position+c.kind.speed*dt,limit);c.speed=Math.max(0,(next-c.position)/dt);c.position=Math.max(c.position,next);ahead=c.position;}}cars=cars.filter(c=>c.position<720);}
function draw(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);}ctx.setTransform(canvas.width/720,0,0,canvas.height/420,0,0);ctx.clearRect(0,0,720,420);ctx.fillStyle='#e8eee0';ctx.fillRect(0,0,720,420);
 for(const [x,y,w,h] of [[25,25,190,105],[485,25,205,105],[25,290,190,105],[485,290,205,105]]){ctx.fillStyle='#d4ddcc';ctx.fillRect(x,y,w,h);ctx.fillStyle='#c3ceba';ctx.fillRect(x+15,y+15,w-30,h-30);}
 ctx.fillStyle='#6a756f';ctx.fillRect(0,155,720,110);ctx.fillRect(305,0,110,420);ctx.strokeStyle='#dee4d7';ctx.lineWidth=2;ctx.setLineDash([12,10]);ctx.beginPath();ctx.moveTo(0,210);ctx.lineTo(720,210);ctx.moveTo(360,0);ctx.lineTo(360,420);ctx.stroke();ctx.setLineDash([]);
 ctx.fillStyle='#dfe7d8';for(let i=0;i<7;i++){ctx.fillRect(285,158+i*15,9,8);ctx.fillRect(308+i*15,135,8,9);}ctx.strokeStyle='#e5ebde';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(299,155);ctx.lineTo(299,210);ctx.moveTo(360,149);ctx.lineTo(415,149);ctx.stroke();
 for(const c of cars){ctx.fillStyle=c.kind.color;const x=c.dir==='ew'?c.position:370+c.lane*20,y=c.dir==='ew'?170+c.lane*20:c.position*420/720;ctx.fillRect(x,y,c.dir==='ew'?c.kind.length:c.kind.width,c.dir==='ew'?c.kind.width:c.kind.length);ctx.fillStyle='#f0f1e9';ctx.fillRect(x+2,y+2,3,3);}
 for(const [dir,x,y] of [['ew',281,235],['ns',431,134]]){ctx.fillStyle='#293b35';ctx.fillRect(x-9,y-14,18,28);ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fillStyle=stage==='green'&&green===dir?'#adf16d':'#ff8570';ctx.fill();}
 ctx.font='12px Arial';ctx.fillStyle='#eef3e8';ctx.fillText('EAST–WEST',30,247);ctx.save();ctx.translate(340,27);ctx.rotate(Math.PI/2);ctx.fillText('NORTH–SOUTH',0,0);ctx.restore();}
function animate(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!paused&&!document.hidden)step(dt);draw();labels();requestAnimationFrame(animate);}labels();requestAnimationFrame(animate);

